//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 10:52:19 PM BRT 
//


package br.com.centralit.citsmart.rest.schema.old;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.centralit.citsmart.rest.schema.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddServiceRequest_QNAME = new QName("http://www.centralit.com.br/services/CITSmartIntegration.XSD", "AddServiceRequest");
    private final static QName _AddServiceRequestResp_QNAME = new QName("http://www.centralit.com.br/services/CITSmartIntegration.XSD", "AddServiceRequestResp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.centralit.citsmart.rest.schema.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtAddServiceRequest }
     * 
     */
    public CtAddServiceRequest createCtAddServiceRequest() {
        return new CtAddServiceRequest();
    }

    /**
     * Create an instance of {@link CtAddServiceRequestResp }
     * 
     */
    public CtAddServiceRequestResp createCtAddServiceRequestResp() {
        return new CtAddServiceRequestResp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtAddServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.centralit.com.br/services/CITSmartIntegration.XSD", name = "AddServiceRequest")
    public JAXBElement<CtAddServiceRequest> createAddServiceRequest(CtAddServiceRequest value) {
        return new JAXBElement<CtAddServiceRequest>(_AddServiceRequest_QNAME, CtAddServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtAddServiceRequestResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.centralit.com.br/services/CITSmartIntegration.XSD", name = "AddServiceRequestResp")
    public JAXBElement<CtAddServiceRequestResp> createAddServiceRequestResp(CtAddServiceRequestResp value) {
        return new JAXBElement<CtAddServiceRequestResp>(_AddServiceRequestResp_QNAME, CtAddServiceRequestResp.class, null, value);
    }

}
