//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 12:13:27 PM BRT 
//


package br.com.centralit.citsmart.rest.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CtNotificationGetByUser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CtNotificationGetByUser">
 *   &lt;complexContent>
 *     &lt;extension base="{}CtMessage">
 *       &lt;sequence>
 *         &lt;element name="NotificationType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OnlyApproval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CtNotificationGetByUser", propOrder = {
    "notificationType",
    "onlyApproval"
})
public class CtNotificationGetByUser
    extends CtMessage
{

    @XmlElement(name = "NotificationType")
    protected int notificationType;
    @XmlElement(name = "OnlyApproval")
    protected int onlyApproval;

    /**
     * Gets the value of the notificationType property.
     * 
     */
    public int getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     */
    public void setNotificationType(int value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the onlyApproval property.
     * 
     */
    public int getOnlyApproval() {
        return onlyApproval;
    }

    /**
     * Sets the value of the onlyApproval property.
     * 
     */
    public void setOnlyApproval(int value) {
        this.onlyApproval = value;
    }

}
