//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 10:30:31 AM BRT 
//


package br.com.centralit.citsmart.rest.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.centralit.citsmart.rest.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Login_QNAME = new QName("", "Login");
    private final static QName _MessageResp_QNAME = new QName("", "MessageResp");
    private final static QName _AddServiceRequestResp_QNAME = new QName("", "AddServiceRequestResp");
    private final static QName _AddServiceRequest_QNAME = new QName("", "AddServiceRequest");
    private final static QName _LoginResp_QNAME = new QName("", "LoginResp");
    private final static QName _Message_QNAME = new QName("", "Message");
    private final static QName _ListTasks_QNAME = new QName("", "ListTasks");
    private final static QName _ListTasksResp_QNAME = new QName("", "ListTasksResp");
    
    private final static QName _NotificationFeedback_QNAME = new QName("", "Notification_Feedback");
    private final static QName _NotificationGetById_QNAME = new QName("", "Notification_GetById");
    private final static QName _NotificationGetByUser_QNAME = new QName("", "Notification_GetByUser");
    private final static QName _NotificationGetReasonsResp_QNAME = new QName("", "Notification_GetReasonsResp");
    private final static QName _NotificationFeedbackResp_QNAME = new QName("", "Notification_FeedbackResp");
    private final static QName _NotificationGetByUserResp_QNAME = new QName("", "Notification_GetByUserResp");
    private final static QName _NotificationGetByIdResp_QNAME = new QName("", "Notification_GetByIdResp");
    private final static QName _NotificationNew_QNAME = new QName("", "Notification_New");
    private final static QName _NotificationGetReasons_QNAME = new QName("", "Notification_GetReasons");
    private final static QName _NotificationNewResp_QNAME = new QName("", "Notification_NewResp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.centralit.citsmart.rest.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtAddServiceRequest }
     * 
     */
    public CtAddServiceRequest createCtAddServiceRequest() {
        return new CtAddServiceRequest();
    }

    /**
     * Create an instance of {@link CtContact }
     * 
     */
    public CtContact createCtContact() {
        return new CtContact();
    }

    /**
     * Create an instance of {@link CtLoginResp }
     * 
     */
    public CtLoginResp createCtLoginResp() {
        return new CtLoginResp();
    }

    /**
     * Create an instance of {@link CtError }
     * 
     */
    public CtError createCtError() {
        return new CtError();
    }

    /**
     * Create an instance of {@link CtMessageResp }
     * 
     */
    public CtMessageResp createCtMessageResp() {
        return new CtMessageResp();
    }

    /**
     * Create an instance of {@link CtMessage }
     * 
     */
    public CtMessage createCtMessage() {
        return new CtMessage();
    }

    /**
     * Create an instance of {@link CtAddServiceRequestResp }
     * 
     */
    public CtAddServiceRequestResp createCtAddServiceRequestResp() {
        return new CtAddServiceRequestResp();
    }

    /**
     * Create an instance of {@link CtLogin }
     * 
     */
    public CtLogin createCtLogin() {
        return new CtLogin();
    }

    public CtListTasks createCtListTasks() {
        return new CtListTasks();
    }

    public CtListTasksResp createCtListTasksResp() {
        return new CtListTasksResp();
    }

    /**
     * Create an instance of {@link CtService }
     * 
     */
    public CtService createCtService() {
        return new CtService();
    }

    /**
     * Create an instance of {@link CtServiceRequest }
     * 
     */
    public CtServiceRequest createCtServiceRequest() {
        return new CtServiceRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtLogin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Login")
    public JAXBElement<CtLogin> createLogin(CtLogin value) {
        return new JAXBElement<CtLogin>(_Login_QNAME, CtLogin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtMessageResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageResp")
    public JAXBElement<CtMessageResp> createMessageResp(CtMessageResp value) {
        return new JAXBElement<CtMessageResp>(_MessageResp_QNAME, CtMessageResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtAddServiceRequestResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddServiceRequestResp")
    public JAXBElement<CtAddServiceRequestResp> createAddServiceRequestResp(CtAddServiceRequestResp value) {
        return new JAXBElement<CtAddServiceRequestResp>(_AddServiceRequestResp_QNAME, CtAddServiceRequestResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtAddServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddServiceRequest")
    public JAXBElement<CtAddServiceRequest> createAddServiceRequest(CtAddServiceRequest value) {
        return new JAXBElement<CtAddServiceRequest>(_AddServiceRequest_QNAME, CtAddServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtLoginResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoginResp")
    public JAXBElement<CtLoginResp> createLoginResp(CtLoginResp value) {
        return new JAXBElement<CtLoginResp>(_LoginResp_QNAME, CtLoginResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Message")
    public JAXBElement<CtMessage> createMessage(CtMessage value) {
        return new JAXBElement<CtMessage>(_Message_QNAME, CtMessage.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "ListTasks")
    public JAXBElement<CtListTasks> createListTasks(CtListTasks value) {
        return new JAXBElement<CtListTasks>(_ListTasks_QNAME, CtListTasks.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "ListTasksResp")
    public JAXBElement<CtListTasksResp> createListTasksResp(CtListTasksResp value) {
        return new JAXBElement<CtListTasksResp>(_ListTasksResp_QNAME, CtListTasksResp.class, null, value);
    }
    
    /**
     * Create an instance of {@link CtNotificationGetByUser }
     * 
     */
    public CtNotificationGetByUser createCtNotificationGetByUser() {
        return new CtNotificationGetByUser();
    }

    /**
     * Create an instance of {@link CtNotificationFeedback }
     * 
     */
    public CtNotificationFeedback createCtNotificationFeedback() {
        return new CtNotificationFeedback();
    }

    /**
     * Create an instance of {@link CtNotificationGetById }
     * 
     */
    public CtNotificationGetById createCtNotificationGetById() {
        return new CtNotificationGetById();
    }

    /**
     * Create an instance of {@link CtNotificationNew }
     * 
     */
    public CtNotificationNew createCtNotificationNew() {
        return new CtNotificationNew();
    }

    /**
     * Create an instance of {@link CtNotification }
     * 
     */
    public CtNotification createCtNotification() {
        return new CtNotification();
    }

    /**
     * Create an instance of {@link CtNotificationGetByIdResp }
     * 
     */
    public CtNotificationGetByIdResp createCtNotificationGetByIdResp() {
        return new CtNotificationGetByIdResp();
    }

    /**
     * Create an instance of {@link CtNotificationFeedbackResp }
     * 
     */
    public CtNotificationFeedbackResp createCtNotificationFeedbackResp() {
        return new CtNotificationFeedbackResp();
    }

    /**
     * Create an instance of {@link CtNotificationGetByUserResp }
     * 
     */
    public CtNotificationGetByUserResp createCtNotificationGetByUserResp() {
        return new CtNotificationGetByUserResp();
    }

    /**
     * Create an instance of {@link CtReason }
     * 
     */
    public CtReason createCtReason() {
        return new CtReason();
    }

    /**
     * Create an instance of {@link CtNotificationNewResp }
     * 
     */
    public CtNotificationNewResp createCtNotificationNewResp() {
        return new CtNotificationNewResp();
    }

    /**
     * Create an instance of {@link CtNotificationGetReasons }
     * 
     */
    public CtNotificationGetReasons createCtNotificationGetReasons() {
        return new CtNotificationGetReasons();
    }

    /**
     * Create an instance of {@link CtNotificationGetReasonsResp }
     * 
     */
    public CtNotificationGetReasonsResp createCtNotificationGetReasonsResp() {
        return new CtNotificationGetReasonsResp();
    }

    /**
     * Create an instance of {@link CtNotificationDetail }
     * 
     */
    public CtNotificationDetail createCtNotificationDetail() {
        return new CtNotificationDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationFeedback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_Feedback")
    public JAXBElement<CtNotificationFeedback> createNotificationFeedback(CtNotificationFeedback value) {
        return new JAXBElement<CtNotificationFeedback>(_NotificationFeedback_QNAME, CtNotificationFeedback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetById")
    public JAXBElement<CtNotificationGetById> createNotificationGetById(CtNotificationGetById value) {
        return new JAXBElement<CtNotificationGetById>(_NotificationGetById_QNAME, CtNotificationGetById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetByUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetByUser")
    public JAXBElement<CtNotificationGetByUser> createNotificationGetByUser(CtNotificationGetByUser value) {
        return new JAXBElement<CtNotificationGetByUser>(_NotificationGetByUser_QNAME, CtNotificationGetByUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetReasonsResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetReasonsResp")
    public JAXBElement<CtNotificationGetReasonsResp> createNotificationGetReasonsResp(CtNotificationGetReasonsResp value) {
        return new JAXBElement<CtNotificationGetReasonsResp>(_NotificationGetReasonsResp_QNAME, CtNotificationGetReasonsResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationFeedbackResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_FeedbackResp")
    public JAXBElement<CtNotificationFeedbackResp> createNotificationFeedbackResp(CtNotificationFeedbackResp value) {
        return new JAXBElement<CtNotificationFeedbackResp>(_NotificationFeedbackResp_QNAME, CtNotificationFeedbackResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetByUserResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetByUserResp")
    public JAXBElement<CtNotificationGetByUserResp> createNotificationGetByUserResp(CtNotificationGetByUserResp value) {
        return new JAXBElement<CtNotificationGetByUserResp>(_NotificationGetByUserResp_QNAME, CtNotificationGetByUserResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetByIdResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetByIdResp")
    public JAXBElement<CtNotificationGetByIdResp> createNotificationGetByIdResp(CtNotificationGetByIdResp value) {
        return new JAXBElement<CtNotificationGetByIdResp>(_NotificationGetByIdResp_QNAME, CtNotificationGetByIdResp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationNew }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_New")
    public JAXBElement<CtNotificationNew> createNotificationNew(CtNotificationNew value) {
        return new JAXBElement<CtNotificationNew>(_NotificationNew_QNAME, CtNotificationNew.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationGetReasons }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_GetReasons")
    public JAXBElement<CtNotificationGetReasons> createNotificationGetReasons(CtNotificationGetReasons value) {
        return new JAXBElement<CtNotificationGetReasons>(_NotificationGetReasons_QNAME, CtNotificationGetReasons.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtNotificationNewResp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notification_NewResp")
    public JAXBElement<CtNotificationNewResp> createNotificationNewResp(CtNotificationNewResp value) {
        return new JAXBElement<CtNotificationNewResp>(_NotificationNewResp_QNAME, CtNotificationNewResp.class, null, value);
    }
}
