//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 03:52:23 PM BRT 
//


package br.com.centralit.citsmart.rest.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import br.com.centralit.bpm.dto.TarefaFluxoDTO;
import br.com.citframework.dto.IDto;
import br.com.citframework.util.DtoAdapter;


/**
 * <p>Java class for CtListTasksResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CtListTasksResp">
 *   &lt;complexContent>
 *     &lt;extension base="{}CtMessageResp">
 *       &lt;group ref="{}Tarefas" maxOccurs="unbounded"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CtListObjects", propOrder = {
    "objetos"
})
public class CtListObjects
    extends CtMessageResp
{

    @XmlElement(name = "Objeto", required = true)
	@XmlJavaTypeAdapter(DtoAdapter.class)	
    protected List<IDto> objetos;

    /**
     * Gets the value of the tarefas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tarefas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarefas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TarefaFluxoDTO }
     * 
     * 
     */
    public List<IDto> getObjetos() {
        if (objetos == null) {
        	objetos = new ArrayList<IDto>();
        }
        return this.objetos;
    }

	public void setObjetos(List<IDto> objetos) {
		this.objetos = objetos;
	}
    
    

}
