//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 09:29:57 PM BRT 
//


package br.com.centralit.citsmart.rest.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CtListTasks complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CtListTasks">
 *   &lt;complexContent>
 *     &lt;extension base="{}CtMessage">
 *       &lt;sequence>
 *         &lt;element name="ListarIncidentes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListarRequisicoes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListarCompras" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListarViagens" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListarRH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CtListTasks", propOrder = {
    "listarIncidentes",
    "listarRequisicoes",
    "listarCompras",
    "listarViagens",
    "listarRH"
})
public class CtListTasks
    extends CtMessage
{

    @XmlElement(name = "ListarIncidentes", required = true)
    protected String listarIncidentes;
    @XmlElement(name = "ListarRequisicoes", required = true)
    protected String listarRequisicoes;
    @XmlElement(name = "ListarCompras", required = true)
    protected String listarCompras;
    @XmlElement(name = "ListarViagens", required = true)
    protected String listarViagens;
    @XmlElement(name = "ListarRH", required = true)
    protected String listarRH;

    /**
     * Gets the value of the listarIncidentes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListarIncidentes() {
        return listarIncidentes;
    }

    /**
     * Sets the value of the listarIncidentes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListarIncidentes(String value) {
        this.listarIncidentes = value;
    }

    /**
     * Gets the value of the listarRequisicoes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListarRequisicoes() {
        return listarRequisicoes;
    }

    /**
     * Sets the value of the listarRequisicoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListarRequisicoes(String value) {
        this.listarRequisicoes = value;
    }

    /**
     * Gets the value of the listarCompras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListarCompras() {
        return listarCompras;
    }

    /**
     * Sets the value of the listarCompras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListarCompras(String value) {
        this.listarCompras = value;
    }

    /**
     * Gets the value of the listarViagens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListarViagens() {
        return listarViagens;
    }

    /**
     * Sets the value of the listarViagens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListarViagens(String value) {
        this.listarViagens = value;
    }

    /**
     * Gets the value of the listarRH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListarRH() {
        return listarRH;
    }

    /**
     * Sets the value of the listarRH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListarRH(String value) {
        this.listarRH = value;
    }

}
