function Temporizador(iconeTimer){var notificacaoAtiva=false;var esconderTempo=false;var self=this;this.listaTimersAtivos=[];var iconeAtivacaoTimer=iconeTimer;this.init=function(){document.getElementById(iconeAtivacaoTimer).addEventListener("click",this.ativarDesativarTimer,true);}
this.ativarDesativarTimer=function(){notificacaoAtiva=!notificacaoAtiva;if(notificacaoAtiva){document.getElementById(iconeAtivacaoTimer).style.opacity='1';notify();}else{document.getElementById(iconeAtivacaoTimer).style.opacity='0.5';notifyEsconder();}}
this.addOuvinte=function(solicitacao){for(var i=0;i<this.listaTimersAtivos.length;i++){if(this.listaTimersAtivos[i]!=null&&this.listaTimersAtivos[i].idComponenteRelogio==solicitacao.idComponenteRelogio){this.listaTimersAtivos[i].idComponenteRelogio=null;this.listaTimersAtivos[i]=null;return;}}
this.listaTimersAtivos.push(solicitacao);}
var notify=function(){if(!notificacaoAtiva){return;}
if(self.listaTimersAtivos==null){return;}else if(self.listaTimersAtivos.length<=0){return;}else{}
for(var i=0;i<self.listaTimersAtivos.length;i++){if(self.listaTimersAtivos[i]!=null){self.listaTimersAtivos[i].atualizar();}}
setTimeout(notify,1000);}
var notifyEsconder=function(){for(var i=0;i<self.listaTimersAtivos.length;i++){if(self.listaTimersAtivos[i]!=null){self.listaTimersAtivos[i].esconderCampo();}}}}
function Solicitacao(_idComponenteRelogio,_idComponenteProgressBar,_dataHoraSolicitacao,_dataHoraLimite){this.idComponenteRelogio=_idComponenteRelogio;this.idComponenteProgressBar=_idComponenteProgressBar;this.dataHoraLimite=_dataHoraLimite;this.dataHoraSolicitacao=_dataHoraSolicitacao;var self=this;this.atualizar=function(){self.contagemRegressiva(this);}
this.esconderCampo=function(){self.esconderTodos(this);}
this.contagemRegressiva=function(solicitacao){var dataCompleta;var horaCompleta;var hoje;var ano;var mes;var dia;var hora;var minuto;var segundo;var futuro;var dataAberturaSolicitacao;var ss;var mm;var hh;var dd;var tempo;dataCompleta=solicitacao.dataHoraSolicitacao.split(" ")[0];horaCompleta=solicitacao.dataHoraSolicitacao.split(" ")[1];ano=NumberUtil.toInteger(dataCompleta.split("-")[0]);mes=NumberUtil.toInteger(dataCompleta.split("-")[1]);dia=NumberUtil.toInteger(dataCompleta.split("-")[2]);hora=NumberUtil.toInteger(horaCompleta.split(":")[0]);minuto=NumberUtil.toInteger(horaCompleta.split(":")[1]);segundo=NumberUtil.toInteger(horaCompleta.split(":")[2].substring(0,horaCompleta.split(":")[2].length-2));dataAberturaSolicitacao=new Date(ano,mes-1,dia,hora,minuto,segundo);hoje=new Date();dataCompleta=solicitacao.dataHoraLimite.split(" ")[0];horaCompleta=solicitacao.dataHoraLimite.split(" ")[1];ano=NumberUtil.toInteger(dataCompleta.split("-")[0]);mes=NumberUtil.toInteger(dataCompleta.split("-")[1]);dia=NumberUtil.toInteger(dataCompleta.split("-")[2]);hora=NumberUtil.toInteger(horaCompleta.split(":")[0]);minuto=NumberUtil.toInteger(horaCompleta.split(":")[1]);segundo=NumberUtil.toInteger(horaCompleta.split(":")[2].substring(0,horaCompleta.split(":")[2].length-2));futuro=new Date(ano,mes-1,dia,hora,minuto,segundo);ss=parseInt((futuro-hoje)/1000);mm=parseInt(ss/60);hh=parseInt(mm/60);dd=parseInt(hh/24);ss=ss-(mm*60);mm=mm-(hh*60);hh=hh-(dd*24);if(dd<=0&&ss<=0&&mm<=0&&hh<=0){tempo="<font color='RED'>"+i18n_message("solicitacao.tempo_esgotado")+"</font>";}else{tempo='';if(dd>0){tempo=tempo+dd+"dia(s), ";}
tempo=tempo+hh+":"+mm+":"+ss;}
var tempoTotalRequisicao=parseInt(futuro-dataAberturaSolicitacao)/1000;var tempoTotalRestante=parseInt(futuro-hoje)/1000;var elementTemp=document.getElementById(solicitacao.idComponenteRelogio);if(elementTemp!=null){document.getElementById(solicitacao.idComponenteRelogio).innerHTML=tempo;}}
this.esconderTodos=function(solicitacao){var elementProg=document.getElementById(solicitacao.idComponenteProgressBar);document.getElementById(solicitacao.idComponenteRelogio).innerHTML=null;}}