-- INÍCIO - MARIO HAYASAKI JUNIOR 30/12/2013

ALTER TABLE PLANOMELHORIA MODIFY (CRIADOPOR VARCHAR2(255 CHAR) );

ALTER TABLE PLANOMELHORIA MODIFY (MODIFICADOPOR VARCHAR2(255 CHAR) );

-- FIM - MARIO HAYASAKI JUNIOR
