//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 08:55:44 AM BRT 
//


package br.com.centralit.citsmart.rest.schema.old;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import br.com.centralit.citsmart.rest.schema.CtServiceRequest;


/**
 * <p>Java class for CtAddServiceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CtAddServiceRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SessionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceRequestSource" type="{http://www.centralit.com.br/services/CITSmartIntegration.XSD}CtServiceRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CtAddServiceRequest", propOrder = {
    "sessionID",
    "serviceRequestSource"
})
public class CtAddServiceRequest {

    @XmlElement(name = "SessionID", required = true)
    protected String sessionID;
    @XmlElement(name = "ServiceRequestSource", required = true)
    protected CtServiceRequest serviceRequestSource;

    /**
     * Gets the value of the sessionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionID() {
        return sessionID;
    }

    /**
     * Sets the value of the sessionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionID(String value) {
        this.sessionID = value;
    }

    /**
     * Gets the value of the serviceRequestSource property.
     * 
     * @return
     *     possible object is
     *     {@link CtServiceRequest }
     *     
     */
    public CtServiceRequest getServiceRequestSource() {
        return serviceRequestSource;
    }

    /**
     * Sets the value of the serviceRequestSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtServiceRequest }
     *     
     */
    public void setServiceRequestSource(CtServiceRequest value) {
        this.serviceRequestSource = value;
    }

}
