//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 08:55:44 AM BRT 
//


package br.com.centralit.citsmart.rest.schema.old;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import br.com.centralit.citsmart.rest.schema.CtError;
import br.com.centralit.citsmart.rest.schema.CtServiceRequest;


/**
 * <p>Java class for CtAddServiceRequestResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CtAddServiceRequestResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="OperationID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;choice>
 *           &lt;element name="Error" type="{http://www.centralit.com.br/services/CITSmartIntegration.XSD}CtError"/>
 *           &lt;element name="ServiceRequestDest" type="{http://www.centralit.com.br/services/CITSmartIntegration.XSD}CtServiceRequest"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CtAddServiceRequestResp", propOrder = {
    "dateTime",
    "operationID",
    "error",
    "serviceRequestDest"
})
public class CtAddServiceRequestResp {

    @XmlElement(name = "DateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlElement(name = "OperationID", required = true)
    protected BigInteger operationID;
    @XmlElement(name = "Error")
    protected CtError error;
    @XmlElement(name = "ServiceRequestDest")
    protected CtServiceRequest serviceRequestDest;

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the operationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOperationID() {
        return operationID;
    }

    /**
     * Sets the value of the operationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOperationID(BigInteger value) {
        this.operationID = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link CtError }
     *     
     */
    public CtError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtError }
     *     
     */
    public void setError(CtError value) {
        this.error = value;
    }

    /**
     * Gets the value of the serviceRequestDest property.
     * 
     * @return
     *     possible object is
     *     {@link CtServiceRequest }
     *     
     */
    public CtServiceRequest getServiceRequestDest() {
        return serviceRequestDest;
    }

    /**
     * Sets the value of the serviceRequestDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtServiceRequest }
     *     
     */
    public void setServiceRequestDest(CtServiceRequest value) {
        this.serviceRequestDest = value;
    }

}
